apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ccgc-final
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Donchka/N01729752_CCGC5504_FINAL_EXAM.git"
    path: "chart"
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true