name: CI Build & Update Helm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  STUDENT_ID: n01729752

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Stop if last commit by github-actions
        run: |
          if [ "$(git log -1 --pretty='%an')" = "github-actions" ]; then
            echo "Last commit was by GitHub Actions bot, stopping to prevent infinite loop."
            exit 0
          fi

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-${{ env.STUDENT_ID }}:${{ env.IMAGE_TAG }}

      - name: Update Helm values.yaml
        run: |
          repo="${{ secrets.DOCKERHUB_USERNAME }}/nginx-${{ env.STUDENT_ID }}"
          tag="${{ env.IMAGE_TAG }}"
          sed -i "s|repository: .*|repository: $repo|" chart/values.yaml
          sed -i "s|tag: .*|tag: \"$tag\"|" chart/values.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add chart/values.yaml
          git commit -m "ci: update Helm image -> $repo:$tag" || echo "no changes to commit"
      - name: Push changes back
        run: |
          if [ -n "${{ secrets.REPO_PAT }}" ]; then
            git push https://x-access-token:${{ secrets.REPO_PAT }}@github.com/${{ github.repository }} HEAD:main
          else
            git push origin HEAD:main
          fi
